// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOIhvLAPHmMmz7xxbrQ0okFr4L37YJ7Y',
    appId: '1:522746161194:web:36bc213e708a9d1d5cbb53',
    messagingSenderId: '522746161194',
    projectId: 'cafesmart-7e206',
    authDomain: 'cafesmart-7e206.firebaseapp.com',
    storageBucket: 'cafesmart-7e206.firebasestorage.app',
    measurementId: 'G-EX142GKE8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCisEBVr-CYU6K5d_fcnYnlh4GtMP5jXGc',
    appId: '1:522746161194:android:e3779fe907dd63d95cbb53',
    messagingSenderId: '522746161194',
    projectId: 'cafesmart-7e206',
    storageBucket: 'cafesmart-7e206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS9MnVm19YjkaAPbUi6nFR191cJuSPnhU',
    appId: '1:522746161194:ios:3516a497a20134865cbb53',
    messagingSenderId: '522746161194',
    projectId: 'cafesmart-7e206',
    storageBucket: 'cafesmart-7e206.firebasestorage.app',
    iosClientId: '522746161194-t9gb593ce9cpfmvtcdec8j0ukbg5s6h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafesmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS9MnVm19YjkaAPbUi6nFR191cJuSPnhU',
    appId: '1:522746161194:ios:3516a497a20134865cbb53',
    messagingSenderId: '522746161194',
    projectId: 'cafesmart-7e206',
    storageBucket: 'cafesmart-7e206.firebasestorage.app',
    iosClientId: '522746161194-t9gb593ce9cpfmvtcdec8j0ukbg5s6h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafesmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDOIhvLAPHmMmz7xxbrQ0okFr4L37YJ7Y',
    appId: '1:522746161194:web:5c4bcb25221399155cbb53',
    messagingSenderId: '522746161194',
    projectId: 'cafesmart-7e206',
    authDomain: 'cafesmart-7e206.firebaseapp.com',
    storageBucket: 'cafesmart-7e206.firebasestorage.app',
    measurementId: 'G-EWXXNZC8SX',
  );
}
